version: 2

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
  disable:
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 5
  max-same-issues: 3