name: Container Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_call: # Allow this workflow to be called by other workflows

jobs:
  container-structure-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
        podman --version
    
    - name: Build container image with Podman
      run: |
        podman build -t darrot:test .
    
    - name: Install container-structure-test
      run: |
        curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
        chmod +x container-structure-test-linux-amd64
        sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
    
    - name: Verify container-structure-test installation
      run: container-structure-test version
    
    - name: Run container structure tests
      run: |
        container-structure-test test \
          --image darrot:test \
          --config tests/container/structure-test.yaml \
          --output json \
          --test-report test-results.json
    
    - name: Display test results
      if: always()
      run: |
        if [ -f test-results.json ]; then
          echo "Container structure test results:"
          cat test-results.json | jq '.'
        else
          echo "No test results file found"
        fi
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: container-structure-test-results
        path: |
          test-results.json
        retention-days: 30
    
    - name: Check test results
      run: |
        if [ -f test-results.json ]; then
          # Check if any tests failed
          FAILED_TESTS=$(cat test-results.json | jq '.Results[] | select(.Pass == false) | length' | wc -l)
          if [ "$FAILED_TESTS" -gt 0 ]; then
            echo "Container structure tests failed!"
            cat test-results.json | jq '.Results[] | select(.Pass == false)'
            exit 1
          else
            echo "All container structure tests passed!"
          fi
        else
          echo "No test results to check"
          exit 1
        fi

  container-security-scan:
    runs-on: ubuntu-latest
    needs: container-structure-tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
        podman --version
    
    - name: Build container image with Podman
      run: |
        podman build -t darrot:test .
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'darrot:test'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'